config/routes.rb
Rails.application.routes.draw do
  
  resources :payment_states
  resources :transactions
  resources :farms

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users

   root 'home#index'

    get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
   patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

   get       'details'                          =>     'farms#details'
    get       'pay'                          =>     'farms#pay'
     get       'about'                          =>     'home#about'
     get       'process'                          =>     'home#process'
     post       'contribute'                          =>     'transactions#contribute'

end

app/models/payment_state.rb
class PaymentState < ActiveRecord::Base
end

app/controllers/payment_states_controller.rb
class PaymentStatesController < ApplicationController
  before_action :set_payment_state, only: [:show, :edit, :update, :destroy]

  # GET /payment_states
  # GET /payment_states.json
  def index
    @payment_states = PaymentState.all
  end

  # GET /payment_states/1
  # GET /payment_states/1.json
  def show
  end

  # GET /payment_states/new
  def new
    @payment_state = PaymentState.new
  end

  # GET /payment_states/1/edit
  def edit
  end

  # POST /payment_states
  # POST /payment_states.json
  def create
    @payment_state = PaymentState.new(payment_state_params)

    respond_to do |format|
      if @payment_state.save
        format.html { redirect_to @payment_state, notice: 'Payment state was successfully created.' }
        format.json { render :show, status: :created, location: @payment_state }
      else
        format.html { render :new }
        format.json { render json: @payment_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_states/1
  # PATCH/PUT /payment_states/1.json
  def update
    respond_to do |format|
      if @payment_state.update(payment_state_params)
        format.html { redirect_to @payment_state, notice: 'Payment state was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_state }
      else
        format.html { render :edit }
        format.json { render json: @payment_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_states/1
  # DELETE /payment_states/1.json
  def destroy
    @payment_state.destroy
    respond_to do |format|
      format.html { redirect_to payment_states_url, notice: 'Payment state was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_state
      @payment_state = PaymentState.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_state_params
      params.require(:payment_state).permit(:transaction_id, :response_code, :amount_after_charges, :client_reference, :description, :external_trans_id, :amount, :charges)
    end
end

app/helpers/payment_states_helper.rb
module PaymentStatesHelper
end

app/views/payment_states/_form.html.erb
<%= simple_form_for(@payment_state) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :transaction_id %>
    <%= f.input :response_code %>
    <%= f.input :amount_after_charges %>
    <%= f.input :client_reference %>
    <%= f.input :description %>
    <%= f.input :external_trans_id %>
    <%= f.input :amount %>
    <%= f.input :charges %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payment_states/edit.html.erb
<h1>Editing Payment State</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_state %> |
<%= link_to 'Back', payment_states_path %>

app/views/payment_states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payment States</h1>

<table>
  <thead>
    <tr>
      <th>Transaction</th>
      <th>Response code</th>
      <th>Amount after charges</th>
      <th>Client reference</th>
      <th>Description</th>
      <th>External trans</th>
      <th>Amount</th>
      <th>Charges</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_states.each do |payment_state| %>
      <tr>
        <td><%= payment_state.transaction_id %></td>
        <td><%= payment_state.response_code %></td>
        <td><%= payment_state.amount_after_charges %></td>
        <td><%= payment_state.client_reference %></td>
        <td><%= payment_state.description %></td>
        <td><%= payment_state.external_trans_id %></td>
        <td><%= payment_state.amount %></td>
        <td><%= payment_state.charges %></td>
        <td><%= link_to 'Show', payment_state %></td>
        <td><%= link_to 'Edit', edit_payment_state_path(payment_state) %></td>
        <td><%= link_to 'Destroy', payment_state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment state', new_payment_state_path %>

app/views/payment_states/new.html.erb
<h1>New Payment State</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_states_path %>

app/views/payment_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction:</strong>
  <%= @payment_state.transaction_id %>
</p>

<p>
  <strong>Response code:</strong>
  <%= @payment_state.response_code %>
</p>

<p>
  <strong>Amount after charges:</strong>
  <%= @payment_state.amount_after_charges %>
</p>

<p>
  <strong>Client reference:</strong>
  <%= @payment_state.client_reference %>
</p>

<p>
  <strong>Description:</strong>
  <%= @payment_state.description %>
</p>

<p>
  <strong>External trans:</strong>
  <%= @payment_state.external_trans_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment_state.amount %>
</p>

<p>
  <strong>Charges:</strong>
  <%= @payment_state.charges %>
</p>

<%= link_to 'Edit', edit_payment_state_path(@payment_state) %> |
<%= link_to 'Back', payment_states_path %>