config/routes.rb
Rails.application.routes.draw do
  
  resources :payment_states
  resources :transactions
  resources :farms

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users

   root 'home#index'

    get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
   patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

   get       'details'                          =>     'farms#details'
    get       'pay'                          =>     'farms#pay'
     get       'about'                          =>     'home#about'
     get       'process'                          =>     'home#process'
     post       'contribute'                          =>     'transactions#contribute'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     @farms = Farm.all.order('id desc').limit(4) 
     # order(:created_at).limit(4)
  end

  def about
  end

  # def process
  # end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="banner">
	<div class="container">
		<div class="w3_agile_banner_top">
			<div class="agile_phone_mail">
				<ul>
					<li>
						<i class="fa fa-phone" aria-hidden="true"></i>+(233)244000000
					</li>
					<li>
						<i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:Coalition@w3layouts.com">agripool@bluecroft.com</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="agileits_w3layouts_banner_nav">
			<nav class="navbar navbar-default">
				<div class="navbar-header navbar-left">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<h1><a class="navbar-brand" href="index.html">Agripool</a></h1>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
					<nav class="cl-effect-13" id="cl-effect-13">
						<ul class="nav navbar-nav">
							<li class="active">
								<%= link_to 'Home',root_path %>
							</li>
							<li>
								<%= link_to 'About Us',about_path %>
							</li>
							<li>

								<%= link_to 'The Process',process_path  %>
							</li>
							<li>
								<%= link_to 'Farms',farms_path %>

							</li>
							<% if user_signed_in? %>

							<li class="dropdown">
								<a data-toggle="dropdown" class="dropdown-toggle" href="#"> <!-- <img alt="" src="images/2.png"> --> <span ><%= current_user.username %></span> <b class="caret"></b> </a>

								<ul class="dropdown-menu extended logout">
									<li>
										<%= link_to ' Check Account'.html_safe %>
									</li>
									<li>
										<%= link_to ' Edit Profile'.html_safe,edit_user_registration_path %>
									</li>
									<li>
										<%= link_to ' Log out'.html_safe,destroy_user_session_path, :method=> 'delete' %>
									</li>

								</ul>
							</li>
							</li>
							<%else%>
							<li>
								<%= link_to "Login", new_user_session_path %>

							</li>
							<%end %>

						</ul>

					</nav>

				</div>
			</nav>
		</div>
		<div class="wthree_banner_info">
			<section class="slider">
				<div class="flexslider">
					<ul class="slides">
						<li>
							<h3>WE FEED OURSELVES </h3>
							<p>
								Agripool gives you the opportunity to fund a farm, empower farmers, learn practical agricultural tips
								<br>
								and share in the harvest.
							</p>

							<div class="agileits_more">
								<ul>
									<li>
										<!-- <a href="#" class="w3ls_banner_more hvr-icon-hang">How it works</a> -->
										<%= link_to 'How it works',process_path ,:class =>"w3ls_banner_more hvr-icon-hang" %>
									</li>
									<li>
										<%= link_to 'Farm now',farms_path ,:class =>"hvr-icon-hang" %>
										<!-- <a href="#" class="hvr-icon-hang" data-toggle="modal" data-target="#myModal">Farm now</a> -->
									</li>
								</ul>
							</div>
						</li>
						<li>
							<h3>WE FEED OURSELVES </h3>
							<p>
								Agripool gives you the opportunity to fund a farm, empower farmers, learn practical agricultural tips
								<br>
								and share in the harvest.
							</p>

							<div class="agileits_more">
								<ul>
									<li>
										<%= link_to 'How it works',process_path ,:class =>"w3ls_banner_more hvr-icon-hang" %>
									</li>
									<li>
										<%= link_to 'Farm now',farms_path, :class =>"hvr-icon-hang"  %>
										<!-- <a href="#" class="hvr-icon-hang" data-toggle="modal" data-target="#myModal">Farm now</a> -->
									</li>
								</ul>
							</div>
						</li>
						<li>
							<h3>WE FEED OURSELVES</h3>
							<p>
								Agripool gives you the opportunity to fund a farm, empower farmers, learn practical agricultural tips
								<br>
								and share in the harvest.
							</p>

							<div class="agileits_more">
								<ul>
									<li>
										<%= link_to 'How it works',process_path ,:class =>"w3ls_banner_more hvr-icon-hang" %>
									</li>
									<li>
										<%= link_to 'Farm now',farms_path ,:class =>"hvr-icon-hang" %>
										<!-- <a href="#" class="hvr-icon-hang" data-toggle="modal" data-target="#myModal">Farm now</a> -->
									</li>
								</ul>
							</div>
						</li>

					</ul>
				</div>
			</section>

		</div>
	</div>
</div>

<div class="section section-benefits">
	<div class="shell-wider">
		<h2 class="section-title">Our Aim</h2><!-- /.section-title -->

		<ul class="benefits">
			<li class="benefit">
				<div class="benefit-image">
					<img width="213" height="225" src="https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image5.png" class="attachment-full size-full" alt="" srcset="https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image5.png 213w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image5-31x33.png 31w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image5-57x60.png 57w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image5-114x120.png 114w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image5-47x50.png 47w" sizes="(max-width: 213px) 100vw, 213px" />
				</div><!-- /.benefit-image -->

				<div class="benefit-content">
					<h3 class="benefit-title">Create a sustainable farming system
					<br>
					</h3><!-- /.benefit-title -->

					<!-- <p> Highest standards of food safety.Reliable fresh produce all year round.Cost effective produce</p> -->
				</div><!-- /.benefit-content -->
			</li><!-- /.benefit -->
			<li class="benefit">
				<div class="benefit-image">
					<img width="160" height="228" src="https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image6.png" class="attachment-full size-full" alt="" srcset="https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image6.png 160w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image6-23x33.png 23w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image6-42x60.png 42w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image6-84x120.png 84w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image6-35x50.png 35w" sizes="(max-width: 160px) 100vw, 160px" />
				</div><!-- /.benefit-image -->

				<div class="benefit-content">
					<h3 class="benefit-title">Impact Farmers through Job Creation
					<br>
					</h3><!-- /.benefit-title -->

					<!-- <p> More sustained farming opportunity and an assured source of livelihood</p> -->
				</div><!-- /.benefit-content -->
			</li><!-- /.benefit -->
			<li class="benefit">
				<div class="benefit-image">
					<img width="207" height="181" src="https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image7.png" class="attachment-full size-full" alt="" srcset="https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image7.png 207w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image7-38x33.png 38w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image7-60x52.png 60w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image7-120x105.png 120w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image7-57x50.png 57w" sizes="(max-width: 207px) 100vw, 207px" />
				</div><!-- /.benefit-image -->

				<div class="benefit-content">
					<h3 class="benefit-title"> Increase overall food production
					<br />
					</h3><!-- /.benefit-title -->

					<!-- <p>Sustainable source of high quality. Low environmental impact.  Optimised water usage.
					</p> -->
				</div><!-- /.benefit-content -->
			</li><!-- /.benefit -->
			<li class="benefit">
				<div class="benefit-image">
					<img width="214" height="206" src="https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image8.png" class="attachment-full size-full" alt="" srcset="https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image8.png 214w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image8-34x33.png 34w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image8-60x58.png 60w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image8-120x116.png 120w, https://www.farmcrowdy.com/wp-content/uploads/2016/08/benefit-image8-52x50.png 52w" sizes="(max-width: 214px) 100vw, 214px" />
				</div><!-- /.benefit-image -->

				<div class="benefit-content">
					<h3 class="benefit-title"> Create a secure farming system with Youth involvement in Agriculture.
					<br />
					</h3><!-- /.benefit-title -->

					<!-- 								<p>A unique way to impact lives.Ease of access to profitable agricultural projects.Return on money
					</p> -->
				</div><!-- /.benefit-content -->
			</li><!-- /.benefit -->
		</ul><!-- /.benefits -->
	</div><!-- /.shell-wider -->
</div><!-- /.section -->

<section class="section section-projects-preview section-solid">
	<div class="shell-wider">
		<h2 class="section-title">Start your farm</h2><!-- /.section-title -->

		<ul class="projects">

			<% @farms.each do |farm| %>
			<div class="project">
				<div class="project-image">

					<%= link_to image_tag (farm.crop_logo),:class=> "attachment-farm_list size-farm_list wp-post-image" %>
					<span> <%= link_to "NOW OPEN",details_path(:id => farm.id) %> </span>
					<!-- <span>NOW <BR><strong>OPEN</strong></span> -->
				</div>

				<div class="project-content">
					<h5><%= farm.crop_name  %></h5>
					<span>GHC<%= farm.amount  %></span>

					<p>
						Returns <%= farm.returns %> per <%= farm.duration %>
					</p>

				</div>
				<span class="project-overlay"> <%= link_to "Start here", details_path(:id => farm.id), :class=> "btn btn-green btn-green-small"%> </span>

				<br>
				<span class="project-overlay"><%= link_to 'Edit Entry', edit_farm_path(farm)%></span>
			</div>

			<%end%>
		</ul><!-- /.projects -->

		<div class="section-actions">
			<%= link_to 'See More Farms',farms_path ,:class =>"btn-green" %>

		</div><!-- /.section-actions -->
	</div><!-- /.shell-wider -->
</section><!-- /.section -->

app/views/home/test.html.erb

<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="/images/favicon.png">
    <title>Agripool</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="robots" content="index, follow">

    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:site" content="@cropital_ph"/>
    <meta name="twitter:creator" content="@cropital_ph"/>
    
    <meta property="og:title" content="Social Impact Investment for farmers at Cropital"/>
    <meta name="twitter:title" content="Social Impact Investment for farmers at Cropital"/>
    <meta itemprop="name" content="Social Impact Investment for farmers at Cropital">
    <meta name="description" content="Cropital is a crowdfunding platform connecting anyone to help finance our farmers. Grow your money, help our farmers."/>
    <meta property="og:description" content="Cropital is a crowdfunding platform connecting anyone to help finance our farmers. Grow your money, help our farmers."/>
    <meta name="twitter:description" content="Cropital is a crowdfunding platform connecting anyone to help finance our farmers. Grow your money, help our farmers."/>
    <meta itemprop="description" content="Cropital is a crowdfunding platform connecting anyone to help finance our farmers. Grow your money, help our farmers.">
    <meta property="og:image" content="/images/thumb.png"/>
    <meta name="twitter:image:src" content="/images/thumb.png"/>
    <meta itemprop="image" content="/images/thumb.png">
    
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
    
    <link rel="icon" href="/images/favicon.png"/>
    <link rel="apple-touch-icon" href="/images/favicon.png"/>
    
    <link rel="stylesheet" href="/assets/bootstrap-theme.css">
    <link rel="stylesheet" href="/assets/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/assets/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/custom.css">
    <link rel="stylesheet" href="/assets/dropzone.css">
    <link rel="stylesheet" href="/assets/lightbox.css">
    <link rel="stylesheet" href="/assets/rangeslider.css">
    <link rel="stylesheet" href="/assets/floatinglabel.css">
    <link rel="stylesheet" href="/assets/datatables.css">
    <link rel="assetsheet" href="/assets/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/admin.css">




    <link rel='stylesheet' id='font-roboto-css'  href='https://fonts.googleapis.com/css?family=Roboto%3A400%2C300%2C700&#038;ver=4.9.6' type='text/css' media='all' />
    <link rel='stylesheet' id='fontawesome-css'  href='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/font-awesome.min.css?ver=1501577965' type='text/css' media='all' />
    <link rel='stylesheet' id='owl-carousel-css'  href='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/owl.carousel/assets/owl.carousel.min.css?ver=1501577970' type='text/css' media='all' />
    <link rel='stylesheet' id='owl-carousel-theme-css'  href='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/owl.carousel/assets/owl.theme.default.min.css?ver=1501577968' type='text/css' media='all' />
    <link rel='stylesheet' id='slick-css'  href='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/slick/slick.css?ver=1501577967' type='text/css' media='all' />
    <link rel='stylesheet' id='magnific-popup-css'  href='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/magnific-popup/magnific-popup.css?ver=1501577970' type='text/css' media='all' />
    <link rel='stylesheet' id='theme-fonts-css'  href='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/fonts.css?ver=1501577911' type='text/css' media='all' />
    <link rel='stylesheet' id='theme-styles-bundle-css'  href='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/bundle.css?ver=1526304720' type='text/css' media='all' />
    <link rel='stylesheet' id='theme-styles-css'  href='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/style.css?ver=1513088743' type='text/css' media='all' />
    <script type='text/javascript' src='https://www.farmcrowdy.com/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
    <script type='text/javascript' src='https://www.farmcrowdy.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
    <script type='text/javascript' src='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/owl.carousel/owl.carousel.min.js?ver=1501577968'></script>
    <script type='text/javascript' src='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/slick/slick.min.js?ver=1501577967'></script>
    <script type='text/javascript' src='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/magnific-popup/jquery.magnific-popup.min.js?ver=1501577970'></script>
    <script type='text/javascript' src='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/assets/vendor/progressbar/progressbar.min.js?ver=1501577966'></script>
    <script type='text/javascript' src='//maps.googleapis.com/maps/api/js?key=AIzaSyCpPF3QGWUkCt6TTpLDlV5pbNAIM5Ec19E&#038;ver=4.9.6'></script>
    <script type='text/javascript' src='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/js/functions.js?ver=1526315202'></script>
    <script type='text/javascript' src='https://www.youtube.com/iframe_api?ver=4.9.6'></script>
    <script type='text/javascript' src='https://www.farmcrowdy.com/wp-content/themes/farmcrowdy/js/custom.js?ver=1512647119'></script>
    <script type='text/javascript' src='https://connect.facebook.net/en_US/all.js?ver=4.9.6'></script>
  </head>

  <body>
    


<header class="header">

        <div class="header-content">
          <!-- <a href="https://www.farmcrowdy.com/" class="">Farmcrowdy</a>

          <a href="https://www.farmcrowdy.com/" class="">Farmcrowdy</a> -->

          <nav class="nav">
            <a href="#" class="btn-menu"> <i class="ico-menu"></i> </a>
            <ul id="menu-main-menu" class="menu">

              <li id="menu-item-7403" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-7403">
                <%= link_to 'Home',root_path  %> 
              </li>
              <li id="menu-item-139" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-139">
                <a href="">FAQs</a>
              </li>
              <li id="menu-item-64" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-64">
               <%= link_to 'Farms',farms_path  %> 
                
              </li>

              <li id="menu-item-2199" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2199">
                <a href="">Contact Us</a>
              </li>
              <li id="menu-item-2199" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2199">
                <%= link_to '<i class="fa fa-key"></i> &nbsp; Log out'.html_safe,destroy_user_session_path, :method=> 'delete' %>
              </li>
            </ul>
          </nav><!-- /.nav -->
        </div><!-- /.header-content -->
      </header><!-- /.header -->


<!-- <nav id="header" class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button id="navbar-toggle" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand text-color-3" href="/"><img class="logo" src="/images/v3.png"></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
         <%#= link_to 'Home',root_path , :class=>"subheading text-color-3" %> 
        </li>
        <li>
          <!-- <a class="subheading text-color-3" href="/learn/how-it-works">How It Works</a> -->
          <%#= link_to 'Farms',farms_path, :class=>"subheading text-color-3"  %> 
       <!--  </li>
        <li>
          <a class="subheading text-color-3" href="/help">Help &amp; Support</a>
        </li>
        
      </ul> -->
     <!--  <div class="navbar-right"> -->
        
       <!--    <a href="/user/login"><button class="btn btn-3" id="login-btn">Log In</button></a> -->

            <%#= link_to "Log in", new_user_session_path,:class=>"btn btn-3" , :id=>"login-btn"%>
            <%#= link_to "Sign up", new_user_registration_path,:class=>"btn btn-1" %>
          <!-- <a href="/user/register"><button class="btn btn-1">Sign-up</button></a> -->
        
    <!--   </div>
    </div>
  </div> -->
<!-- </nav> -->


<div class="parallax-window-header" data-parallax="scroll" data-image-src="/assets/how.jpg" >

  <div class="container pages-md">
    <div class="row center">
      <h2><strong>Agripool helps investments in farms</strong></h4>
      <h3 class="lh-xs mobile-padding-lr">Here's how you can be part of the mission</h3>
    </div>
  </div>
</div>

<div class="content-frame-pln">
  <div class="row no-m">
    <div class="col-md-4 center bg-how-1 no-padding">
      <img class="icon padding-img" src="/assets/how-1.png" height="260px">
    </div>
    <div class="col-md-8">
      <h3 class="text-color-5 lh-xs">Step 1<br><strong>Create an account</strong></h3>
      <p class="text-color-2 text-md">Account is automatically created when you sign-up and register.</p>
      <br>
      <br>
    </div>
  </div>
</div>
<div class="content-frame-pln">
  <div class="row no-m">
    <div class="col-md-4 center bg-how-2 no-padding mobile-on">
      <img class="icon padding-img" src="/assets/how-2.png" height="260px">
    </div>
    <div class="col-md-8 padding">
      <h3 class="text-color-5 lh-xs">Step 2<br><strong>Contribute to your wallet</strong></h3>
      <p class="text-color-2 text-md">You can contribute any amount to the wallet till you have reached a targeted amount to fund a farm you are interested in. Contributions to a specific farm will not be accepted when farm starts. You can contribute to more than one farm</p>
      <br>
    </div>
    <div class="col-md-4 center bg-how-2 no-padding mobile-off">
      <img class="icon padding-img" src="/assets/how-2.png" height="260px">
    </div>
  </div>
</div>
<div class="content-frame-pln">
  <div class="row no-m">
    <div class="col-md-4 center bg-how-1 no-padding">
      <img class="icon padding-img" src="/assets/how-3.png" height="260px">
    </div>
    <div class="col-md-8 padding">
      <h3 class="text-color-5 lh-xs">Step 3<br><strong>Choose Farm</strong></h3>
      <p class="text-color-2 text-md">When your target is reached, you select a package from the farm shop, and contribute to that particular farm. Contributions will be reflected on the dashboard immediately.</p>
      <br>
    </div>
  </div>
</div>
<div class="content-frame-pln">
  <div class="row no-m">
    <div class="col-md-4 center bg-how-2 no-padding mobile-on">
      <img class="icon padding-img" src="/assets/how-4.png" height="260px">
    </div>
    <div class="col-md-8 padding">
      <h3 class="text-color-5">Step 4<br><strong>Farm Updates</strong></h3>
      <p class="text-color-2 text-md">Track your farm through videos, pictures and text of activities on the farm (start to end of farm). Receive notifications of the activities on the farm and occasional visits to the farm. 
    </div>
    <div class="col-md-4 center bg-how-2 no-padding mobile-off">
      <!-- <img class="icon padding-img" src="/images/static-pages/how-4.png" height="260px"> -->
    </div>
  </div>
</div>

<div class="content-frame-pln">
  <div class="row no-m">
    <div class="col-md-4 center bg-how-1 no-padding">
      <img class="icon padding-img" src="/assets/how-3.png" height="260px">
    </div>
    <div class="col-md-8 padding">
      <h3 class="text-color-5 lh-xs">Step 3<br><strong>Get Profit on contributions</strong></h3>
      <p class="text-color-2 text-md">After a successful season, all produce is sold. Returns are subsequently distributed to our subscribers.</p>
      <br>
    </div>
  </div>
</div>





<br>

    
    <!--TEMPLATES-->
    <script type="text/javascript" src="/assets/jst.js"></script>
    <!--TEMPLATES END-->

    <script src="/assets/_jquery-1.11.3.min.js"></script>
    <script src="/assets/bootstrap.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/parallax.min.js"></script>
    <script src="/assets/dropzone.js"></script>
    <script src="/assets/lightbox.min.js"></script>
    <script src="/assets/rangeslider.min.js"></script>
    <script src="/assets/common.js"></script>
    <script src="/assets/floatinglabel.js"></script>
    <script src="/assets/jquery.dataTables.js"></script>
    <script src="/assets/_moment.min.js"></script>
    <script src="/assets/underscore.min.js"></script>
    <script src="/assets/priceformat.min.js"></script>
		
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script src="/assets/custom.js"></script>

      
  </body>
</html>