config/routes.rb
Rails.application.routes.draw do
  
  resources :payment_states
  resources :transactions
  resources :farms

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users

   root 'home#index'

    get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
   patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

   get       'details'                          =>     'farms#details'
    get       'pay'                          =>     'farms#pay'
     get       'about'                          =>     'home#about'
     get       'process'                          =>     'home#process'
     post       'contribute'                          =>     'transactions#contribute'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
require 'base64'
#require 'sinatra'
require 'json'
require 'nokogiri'
#require 'sinatra/activerecord'
require 'yaml'
require 'faraday'
require 'net/http'
require 'uri'
require 'savon'
require 'digest/md5'
require 'openssl'
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  
CLIENT_ID = 'dtajuwmo'
CLIENT_SECRET ='xgvbtkvc' 
CALLBACK_URL = "http://144.217.165.180:6007/primary_callback"  
DESCRIPTION = "Agripool contribution"
REQHDR = {'Content-Type'=>'Application/json','timeout'=>'180'}

def uniqueCode
  time=Time.new
  strtm = time.strftime("AGR"+"%y%m%d%L%H%M")
  return strtm
end

def tranSaver(customer_name,customer_mobile_number,amount,u_code,channel,token,farm_id,user_id,trans_description,status)
  time = Time.now.strftime('%Y-%m-%d %H:%M:%S')

  Transaction.create(customer_name: customer_name, customer_mobile_number: customer_mobile_number,amount: amount,
                            u_code: u_code, channel: channel,token: token, farm_id: farm_id, user_id: user_id ,trans_description: trans_description,status: status,
                            created_at: time)
end


def mobileMoneyReq(customerName,customerMsisdn,channel,amount,primaryCallbackUrl,description,token,farm_id,user_id,status)

  clientReference=uniqueCode
  url = 'https://api.hubtel.com'
  url_endpoint = '/v1/merchantaccount/merchants/HM0307180001/receive/mobilemoney'
 
  conn = Faraday.new(url: url, headers: REQHDR, ssl: { verify: false }) do |f|
          f.response :logger
          f.adapter Faraday.default_adapter
   end
   
   
   tranSaver(customerName,customerMsisdn,amount,clientReference,channel,token,farm_id,user_id,description,status)
   
   # @transaction = Transaction.new({:customer_name => customer_name,:customer_mobile_number => customer_mobile_number, :amount => amount ,:channel=> channel,:token=> token,:status=> status,:farm_id=> farm_id,:user_id=> user_id})
   # @transaction.save
   
payload={
     :CustomerName => customerName,
     :CustomerMsisdn => customerMsisdn,
     :Channel => channel,
     :Amount => amount,
     :PrimaryCallbackUrl => primaryCallbackUrl,
     :Description => description,
     :ClientReference=> clientReference,
     :Token => token
 }

json_payload=JSON.generate(payload)
msg_endpoint="#{json_payload}"

auth = 'Basic ' + Base64.encode64( "#{CLIENT_ID}:#{CLIENT_SECRET}" ).chomp

   res = conn.post do |req|
          req.url url_endpoint
          req.options.timeout = 30           # open/read timeout in seconds
          req.options.open_timeout = 30      # connection open timeout in seconds
          req['Authorization'] = "#{auth}"
          req.body = json_payload
          logger.info req.url url_endpoint
   end
        logger.info "------------------------------------------"
        logger.info "Result from API: #{res.body}"
        logger.info "----------------------------------------------"
end


# def processPayment(customerName,customerMsisdn,channel,amount,token) 
# 
   # mobileMoneyReq(customerName,customerMsisdn,channel,amount,CALLBACK_URL,DESCRIPTION,token)
# 
# end

def contribute
   @farm = Farm.new
     @make_transaction = Transaction.new
   logger.info "---------------------------Contribute PARAMS---------------------------------"
    customer_name = params[:transaction][:customer_name]
    customer_mobile_number = params[:transaction][:customer_mobile_number]
    amount = params[:transaction][:amount]
    channel = params[:transaction][:channel]
    token = params[:transaction][:token]
    status = params[:transaction][:status] 
    farm_id = params[:transaction][:farm_id] 
    user_id = params[:transaction][:user_id] 
    
      
    mobileMoneyReq(customer_name,customer_mobile_number,channel,amount,CALLBACK_URL,DESCRIPTION,token,farm_id,user_id,status)
   
 render body: "In progress"
    
end




  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
     @farm = Farm.new
     @make_transaction = Transaction.new
     
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:customer_name, :customer_mobile_number, :channel, :amount, :description, :token, :status)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :customer_name %>
    <%= f.input :customer_mobile_number %>
    <%= f.input :channel %>
    <%= f.input :amount %>
    <%= f.input :description %>
    <%= f.input :token %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Customer mobile number</th>
      <th>Channel</th>
      <th>Amount</th>
      <th>Description</th>
      <th>Token</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.customer_name %></td>
        <td><%= transaction.customer_mobile_number %></td>
        <td><%= transaction.channel %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.token %></td>
        <td><%= transaction.status %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @transaction.customer_name %>
</p>

<p>
  <strong>Customer mobile number:</strong>
  <%= @transaction.customer_mobile_number %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @transaction.channel %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Token:</strong>
  <%= @transaction.token %>
</p>

<p>
  <strong>Status:</strong>
  <%= @transaction.status %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>